# application.properties
spring.datasource.url=${DB_URL:jdbc:h2:mem:tastemap;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

naver.client.id=${NAVER_CLIENT_ID:}
naver.client.secret=${NAVER_CLIENT_SECRET:}
naver.url.search.local=${NAVER_SEARCH_LOCAL_URL:https://openapi.naver.com/v1/search/local.json}
naver.url.search.image=${NAVER_SEARCH_IMAGE_URL:https://openapi.naver.com/v1/search/image}

springdoc.api-docs.path=/v3/api-docs
# swagger UI ?? ??? /swagger-ui/index.html ??? ?? ? ?? ??
springdoc.swagger-ui.path=/swagger-ui.html
